use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::SystemTime;
use tauri::menu::{MenuBuilder, MenuItemBuilder, SubmenuBuilder};
use tauri::{Emitter, Manager};
use walkdir::WalkDir;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SourceFile {
    pub path: String,
    pub text: String,
    pub lang: String,
    /// True if the file looks like a test (e.g. __tests__, *.test.*, *_test.go).
    #[serde(default)]
    pub is_test: bool,
    /// True if the file is a build artifact, generated file, or vendored copy.
    #[serde(default)]
    pub is_generated: bool,
}

#[derive(Debug, Serialize, Deserialize, Clone, Default)]
pub struct ScanStats {
    pub total_files: usize,
    pub parsed_files: usize,
    pub skipped_files: usize,
    pub by_language: HashMap<String, usize>,
    pub test_files: usize,
    pub generated_files: usize,
}

const SUPPORTED_EXTENSIONS: &[(&str, &[&str])] = &[
    ("typescript", &["ts", "mts", "cts"]),
    ("tsx", &["tsx"]),
    ("javascript", &["js", "jsx", "mjs", "cjs"]),
    ("python", &["py"]),
    ("go", &["go"]),
    ("rust", &["rs"]),
    ("java", &["java"]),
    ("c", &["c", "h"]),
    ("cpp", &["cpp", "cc", "cxx", "hpp", "hh"]),
];

fn lang_for_path(path: &Path) -> Option<&'static str> {
    let ext = path.extension()?.to_str()?.to_lowercase();
    if path.to_str()?.ends_with(".d.ts") {
        return None;
    }
    for (lang, exts) in SUPPORTED_EXTENSIONS {
        if exts.contains(&ext.as_str()) {
            return Some(lang);
        }
    }
    None
}

/// `.h` files are ambiguous between C and C++. If the path ends in `.h`
/// and the contents look like C++ (class/struct/namespace declarations,
/// templates, or qualified call syntax), prefer the C++ grammar.
fn resolve_lang(path: &Path, text: &str) -> Option<&'static str> {
    let lang = lang_for_path(path)?;
    if lang != "c" {
        return Some(lang);
    }
    if path.to_str().map(|p| !p.to_lowercase().ends_with(".h")).unwrap_or(true) {
        return Some(lang);
    }
    let head = &text[..text.len().min(8000)];
    let cpp_markers = [
        "\nclass ", "\nstruct ", "\nnamespace ", "\ntemplate <",
        "::", "\n#include <",
    ];
    for marker in cpp_markers {
        if head.contains(marker) {
            return Some("cpp");
        }
    }
    Some(lang)
}

const SKIP_DIRS: &[&str] = &[
    "node_modules", ".git", "dist", "dist-mcp", "build", "out",
    ".next", ".nuxt", "coverage", "vendor", ".cache", ".turbo",
    "target", ".gradle", ".idea", ".vscode", ".next",
    "bower_components", "jspm_packages", "elm-stuff",
];

const MAX_FILES: usize = 4000;
const MAX_FILE_BYTES: u64 = 1_500_000;

const TEST_PATH_HINTS: &[&str] = &[
    "__tests__", "/test/", "/tests/", "_test.", ".test.", ".spec.",
    "test_", "/spec/", "/__mocks__/",
];

const TEST_FILE_PATTERNS: &[&str] = &[
    ".test.", ".spec.", "_test.", "_spec.", "test_", "Test.",
    "Tests.", "Spec.",
];

const GENERATED_HINTS: &[&str] = &[
    "@generated", "@autogenerated", "auto-generated", "DO NOT EDIT",
    "This file is auto-generated", "Code generated by",
    "Generated by",
];

fn is_test_file(path: &Path) -> bool {
    let s = path.to_string_lossy().to_lowercase();
    let normalized = s.replace('\\', "/");
    if TEST_PATH_HINTS.iter().any(|hint| normalized.contains(hint)) {
        return true;
    }
    let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
    let lower = name.to_lowercase();
    if TEST_FILE_PATTERNS.iter().any(|p| lower.contains(&p.to_lowercase())) {
        return true;
    }
    false
}

fn is_generated_file(path: &Path, text: &str) -> bool {
    if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
        let lower = name.to_lowercase();
        if lower.ends_with(".min.js") || lower.ends_with(".min.css")
            || lower.ends_with(".bundle.js") || lower.ends_with(".d.ts")
            || lower.ends_with(".pb.go") || lower.ends_with(".generated.go")
            || lower.contains(".generated.") || lower.contains("_pb2.") {
            return true;
        }
    }
    let head = text.lines().take(15).collect::<Vec<_>>().join("\n");
    GENERATED_HINTS.iter().any(|hint| head.contains(hint))
}

#[tauri::command]
fn scan_directory(path: String) -> Result<Vec<SourceFile>, String> {
    let root = PathBuf::from(&path);
    if !root.exists() {
        return Err(format!("Directory does not exist: {}", path));
    }
    if !root.is_dir() {
        return Err(format!("Path is not a directory: {}", path));
    }

    let mut files = Vec::new();
    for entry in WalkDir::new(&root)
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| {
            if e.file_type().is_dir() {
                if let Some(name) = e.file_name().to_str() {
                    if SKIP_DIRS.contains(&name) || name.starts_with('.') {
                        return false;
                    }
                }
            }
            true
        })
    {
        if files.len() >= MAX_FILES {
            break;
        }
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let lang = match lang_for_path(path) {
            Some(l) => l,
            None => continue,
        };
        let metadata = match entry.metadata() {
            Ok(m) => m,
            Err(_) => continue,
        };
        if metadata.len() > MAX_FILE_BYTES {
            continue;
        }
        let text = match fs::read_to_string(path) {
            Ok(t) => t,
            Err(_) => continue,
        };
        let resolved = match resolve_lang(path, &text) {
            Some(l) => l,
            None => continue,
        };
        let relative = path
            .strip_prefix(&root)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");
        let is_test = is_test_file(path);
        let is_generated = is_generated_file(path, &text);
        files.push(SourceFile {
            path: relative,
            text,
            lang: resolved.to_string(),
            is_test,
            is_generated,
        });
    }
    Ok(files)
}

#[tauri::command]
fn read_file(path: String) -> Result<String, String> {
    fs::read_to_string(&path).map_err(|e| format!("Failed to read {}: {}", path, e))
}

#[tauri::command]
fn file_exists(path: String) -> bool {
    Path::new(&path).exists()
}

#[tauri::command]
fn get_app_info() -> serde_json::Value {
    serde_json::json!({
        "version": env!("CARGO_PKG_VERSION"),
        "name": "Meridian",
        "platform": std::env::consts::OS,
        "arch": std::env::consts::ARCH,
    })
}

#[tauri::command]
fn compute_stats(files: Vec<SourceFile>) -> ScanStats {
    let mut stats = ScanStats::default();
    stats.total_files = files.len();
    for f in &files {
        *stats.by_language.entry(f.lang.clone()).or_insert(0) += 1;
        if f.is_test {
            stats.test_files += 1;
        }
        if f.is_generated {
            stats.generated_files += 1;
        }
        if f.text.is_empty() {
            stats.skipped_files += 1;
        } else {
            stats.parsed_files += 1;
        }
    }
    stats
}

#[tauri::command]
fn export_snapshot(
    path: String,
    payload: serde_json::Value,
) -> Result<(), String> {
    let json = serde_json::to_string_pretty(&payload)
        .map_err(|e| format!("Failed to serialize: {}", e))?;
    fs::write(&path, json).map_err(|e| format!("Failed to write {}: {}", path, e))
}

#[tauri::command]
fn import_snapshot(path: String) -> Result<serde_json::Value, String> {
    let text = fs::read_to_string(&path)
        .map_err(|e| format!("Failed to read {}: {}", path, e))?;
    serde_json::from_str(&text)
        .map_err(|e| format!("Failed to parse JSON in {}: {}", path, e))
}

#[tauri::command]
fn open_in_editor(path: String) -> Result<(), String> {
    let target = PathBuf::from(&path);
    if path.trim().is_empty() {
        return Err("Path is empty".to_string());
    }
    if !target.exists() {
        return Err(format!("Path does not exist: {}", path));
    }

    #[cfg(target_os = "windows")]
    {
        // Pass the path as a single quoted argument to avoid injection via
        // characters like '&' that cmd would otherwise interpret.
        let path_str = target.to_string_lossy().to_string();
        std::process::Command::new("cmd")
            .args(&["/C", "start", "", &path_str])
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    #[cfg(target_os = "macos")]
    {
        std::process::Command::new("open")
            .arg(&target)
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    #[cfg(target_os = "linux")]
    {
        std::process::Command::new("xdg-open")
            .arg(&target)
            .spawn()
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Compute a per-file mtime snapshot for the given paths. Returns a
/// map of path -> last_modified_unix_seconds. The frontend can diff
/// this against a previous snapshot to know which files changed.
#[tauri::command]
fn get_mtimes(paths: Vec<String>) -> Result<HashMap<String, u64>, String> {
    let mut out = HashMap::new();
    for p in paths {
        if let Ok(meta) = fs::metadata(&p) {
            if let Ok(mtime) = meta.modified() {
                if let Ok(dur) = mtime.duration_since(SystemTime::UNIX_EPOCH) {
                    out.insert(p, dur.as_secs());
                }
            }
        }
    }
    Ok(out)
}

/// Cheap directory walk that returns every (file_path, mtime) for the
/// given root. Used by the frontend's keep-watch loop to detect
/// changes without re-parsing the whole project.
#[tauri::command]
fn watch_snapshot(root: String) -> Result<HashMap<String, u64>, String> {
    let root_path = PathBuf::from(&root);
    if !root_path.is_dir() {
        return Err(format!("Not a directory: {}", root));
    }
    let mut out = HashMap::new();
    for entry in WalkDir::new(&root_path).follow_links(false).into_iter().filter_entry(|e| {
        if e.file_type().is_dir() {
            if let Some(name) = e.file_name().to_str() {
                return !SKIP_DIRS.contains(&name) && !name.starts_with('.');
            }
        }
        true
    }) {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        if lang_for_path(path).is_none() {
            continue;
        }
        // `watch_snapshot` doesn't read the file, so for `.h` we can't
        // disambiguate C from C++. Both C and C++ headers are watched;
        // the language only matters when a full survey is built.
        if let Ok(meta) = entry.metadata() {
            if let Ok(mtime) = meta.modified() {
                if let Ok(dur) = mtime.duration_since(SystemTime::UNIX_EPOCH) {
                    let rel = path
                        .strip_prefix(&root_path)
                        .unwrap_or(path)
                        .to_string_lossy()
                        .replace('\\', "/");
                    out.insert(rel, dur.as_secs());
                }
            }
        }
    }
    Ok(out)
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_store::Builder::default().build())
        .setup(|app| {
            let open_folder = MenuItemBuilder::new("Open Folder…")
                .id("open_folder")
                .accelerator("CmdOrCtrl+O")
                .build(app)?;
            let view_specimen = MenuItemBuilder::new("View Specimen")
                .id("view_specimen")
                .accelerator("CmdOrCtrl+Shift+S")
                .build(app)?;
            let new_chart = MenuItemBuilder::new("New Chart")
                .id("new_chart")
                .accelerator("CmdOrCtrl+N")
                .build(app)?;
            let resurvey = MenuItemBuilder::new("Re-survey")
                .id("resurvey")
                .accelerator("CmdOrCtrl+R")
                .build(app)?;
            let quit = MenuItemBuilder::new("Quit")
                .id("quit")
                .accelerator("CmdOrCtrl+Q")
                .build(app)?;
            let export = MenuItemBuilder::new("Export Chart as JSON…")
                .id("export_chart")
                .accelerator("CmdOrCtrl+E")
                .build(app)?;
            let import = MenuItemBuilder::new("Import Chart…")
                .id("import_chart")
                .accelerator("CmdOrCtrl+I")
                .build(app)?;

            let file_menu = SubmenuBuilder::new(app, "File")
                .item(&open_folder)
                .item(&view_specimen)
                .separator()
                .item(&resurvey)
                .item(&new_chart)
                .item(&export)
                .item(&import)
                .separator()
                .item(&quit)
                .build()?;

            let edit_menu = SubmenuBuilder::new(app, "Edit")
                .undo()
                .redo()
                .separator()
                .cut()
                .copy()
                .paste()
                .select_all()
                .build()?;

            let toggle_devtools = MenuItemBuilder::new("Toggle Devtools")
                .id("toggle_devtools")
                .accelerator("F12")
                .build(app)?;
            let view_menu = SubmenuBuilder::new(app, "View")
                .item(&toggle_devtools)
                .build()?;

            let about = MenuItemBuilder::new("About Meridian")
                .id("about")
                .build(app)?;
            let help_menu = SubmenuBuilder::new(app, "Help").item(&about).build()?;

            let menu = MenuBuilder::new(app)
                .item(&file_menu)
                .item(&edit_menu)
                .item(&view_menu)
                .item(&help_menu)
                .build()?;

            app.set_menu(menu)?;

            let window = app.get_webview_window("main").unwrap();
            window.on_menu_event(move |app_handle, event| {
                let id = event.id().as_ref();
                if id == "quit" {
                    app_handle.exit(0);
                    return;
                }
                if id == "toggle_devtools" {
                    #[cfg(debug_assertions)]
                    if let Some(w) = app_handle.get_webview_window("main") {
                        if w.is_devtools_open() {
                            w.close_devtools();
                        } else {
                            w.open_devtools();
                        }
                    }
                    return;
                }
                let _ = app_handle.emit("menu", id);
            });

            #[cfg(debug_assertions)]
            if let Some(window) = app.get_webview_window("main") {
                window.open_devtools();
            }
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            scan_directory,
            read_file,
            file_exists,
            get_app_info,
            compute_stats,
            export_snapshot,
            import_snapshot,
            open_in_editor,
            get_mtimes,
            watch_snapshot,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
